### PR TITLE
Add explicit nullable type where required

### PR DESCRIPTION
**Pull request by alexandre-daubois**
Hello 👋 In the path to make Symfony fully compatible with the last PHP version, we'd like to upgrade the code to be deprecation free in PHP 8.4. Indeed, LibDNS is used by `amphp/dns`. This code update requires PHP 7.1, but I think it's safe to have this minimal requirement now. 🙂 

Related to https://github.com/symfony/symfony/issues/54180

### CODE REVIEW

**Comment by nicolas-grekas** [comment]
@DaveRandom could you please merge this one and release it as v2.2.0 (because of the PHP version dump)? I'd help a lot with Symfony :pray:

**Review by kelunik — APPROVED** [review]

**Comment by kelunik** [comment]
@alexandre-daubois @nicolas-grekas Thanks!

**Comment by kelunik** [comment]
Tagged as v2.1.0 (not v2.2.0).

**Comment by alexandre-daubois** [comment]
Thanks! 🙏

**Pull request merged**
