### PR TITLE
Fixed bug in packet encoding and RData iteration.

### PR DESCRIPTION
**Pull request by trowski**
I'm implementing an asynchronous DNS resolver (and eventually server) with your library and ran into a couple of bugs. These small modifications seem to have solved my problems.

### CODE REVIEW

**Comment by DaveRandom** [comment]
Looks great, thanks!

**Comment by trowski** [comment]
Can you please tag the merge with v1.0.1 so composer will pull that version?

Also I would love to see some documentation and tests. I feel like I'm pulling the library completely apart just so I can use it. Those bugs also would have been found in short order if there were some tests.

**Comment by DaveRandom** [comment]
This whole project could really use some love, it's been largely ignored (by me, anyway) for a long time. I'm about to go on holiday for a couple of weeks but I'm certainly prepared to put some effort into getting this a bit more professional-looking and user-friendly when I get back. @rdlowrey and @Danack both have commit access to move on this before then (if they have time).

I've just pushed a few commits that fix a few other small issues found by static analysis, as well as some code style/consistency fixes - this was initially written in a text editor without the rich tooling that PHP Storm provides. There are also a couple of efficiency improvements, and I've migrated the directory layout to PSR-4 style, and updated composer.json accordingly.

Version 1.0.1 is tagged.

**Comment by trowski** [comment]
I have some timelines I need to meet in the next month, but I will be happy to help you update the library.

I have some ideas for it, the first being adding interfaces for many of the types and then type-hinting against those interfaces instead of concrete classes for better extensibility.

If you're curious about what I'm building, it is a [DNS component](//github.com/icicleio/Dns) for [Icicle](//github.com/icicleio/Icicle), a library for writing asynchronous code in PHP using promises and coroutines.

**Pull request merged**
